name: coverage

on:
  push:
    branches:
      - 'feature/**'
      - 'release/**'
      - 'develop'
      - 'master'
  pull_request:
    branches: [ "main" ]

env:
  CARGO_INCREMENTAL: false
  CARGO_TERM_COLOR: always
  RUST_LOG: info
  RUST_BACKTRACE: full
  REPO_MSRV: "1.70"

jobs:
  test-coverage:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install cargo-nextest and cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest,cargo-llvm-cov
          
      - name: caching
        uses: Swatinem/rust-cache@v2
          
      - name: Run tests
        shell: bash
        run: |
          set -e
          cargo test -- --test-threads=1

      - name: Generate coverage report
        run: |
          set -e
          cargo generate-lcov