name: coverage

on:
  push:
    branches:
      - 'feature/**'
      - 'release/**'
      - 'develop'
      - 'master'
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-coverage:

    runs-on: ubuntu-latest

    steps:
      - name: checkout repo- name
        uses: actions/checkout@v4
      - name: Install cargo-nextest and cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest,cargo-llvm-cov      
      - name: Run test coverage
        run: cargo coverage
        # run: cargo test -- --test-threads=1