name: coverage

on:
  push:
    branches:
      - 'feature/**'
      - 'release/**'
      - 'develop'
      - 'master'
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run code coverage
      # run: cargo coverage
      run: cargo test -- --test-threads=1