name: coverage

on:
  workflow_call:
    inputs:
      target-os:
        required: true
        type: string
      rust-version:
        required: true
        type: string
    secrets:
      CODECOV_TOKEN:
        required: true


env:
  CARGO_INCREMENTAL: false
  CARGO_TERM_COLOR: always
  RUST_LOG: info
  RUST_BACKTRACE: full

jobs:
  generate-lcov:
    name: Generate line coverage
    # needs: test-coverage
    runs-on: ${{ inputs.target-os }}

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install Repo MSRV toolchain
        run: |
          rustup toolchain install ${{ inputs.rust-version }} --no-self-update \
            --profile=minimal -c llvm-tools
          cargo -V        

      - name: Install cargo-nextest and cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest,cargo-llvm-cov
          
      - name: caching
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: test-${{ inputs.target-os }}

      - name: Generate line coverage file
        id: coverage
        shell: bash
        run: |
          set -e
          cargo generate-lcov

      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v3
        if: steps.coverage.outcome == 'success'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: true
          verbose: true