name: ci tags

on:
  push:
    tags:
      - "*"

jobs:
  call-test:
    uses: ./.github/workflows/reusable-test.yml
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]    
    with:
      target-os: ${{ matrix.os }}
      rust-version: ${{ vars.RUST_VERSION }}
  call-release:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    uses: ./.github/workflows/reusable-release.yml
    with:
      target-os: ${{ matrix.os }}
      rust-version: ${{ vars.RUST_VERSION }}
