name: test

on:
  workflow_call:
    inputs:
      target-os:
        required: true
        type: string
      rust-version:
        required: true
        type: string

env:
  CARGO_INCREMENTAL: false
  CARGO_TERM_COLOR: always
  RUST_LOG: info
  RUST_BACKTRACE: full

jobs:
  test:
    name: Run tests
    runs-on: ${{ inputs.target-os }}
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install Repo MSRV toolchain
        run: |
          rustup toolchain install ${{ inputs.rust-version }} \
            --no-self-update --profile=minimal

      - name: caching
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: test-${{ inputs.target-os }}

      - name: Run tests
        shell: bash
        run: |
          set -e
          cargo test -- --test-threads=1
